### ISSUE TITLE
✨ [Feature request]: Hackathon: ReactPlay Landing page banner update

### ISSUE THREAD

**Issue by koustov** [reactplay/activities#10]
The idea of this feature is to create a code-level switch to show the `ongoing activity` banner on reactplay landing page. 

Usually, the reactplay.io home page will render a predefined banner related to the community. However when the community goes into a very specific activity, a switch will be flipped and the banner will be replaced with the event one,

To put it into context, reactplay is going to co-host a **hackathon** very soon. To emphasize the event, the home page banner should be replaced with hackathon-related image. Upon clicking this, the page will redirect to https://hustles.reactplay.io/

Here goes the current home page banner that appears in the first fold of the page view.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/3633137/188666154-90a6cc91-a85b-4f10-a0a5-ba8254bc3f5a.png">

- We want to get rid of the video
- Want to have a clear communication that we will be hosting a Hackathon(Call it ReactPlay Hackathon for now)
- Should have the button to go to the register page.
- Should have the button to "share about it"
- Should have exciting graphics for users to relate it is a Hackathon
- Should have the way to project the sponsor who is sponsoring the hackathon
- The banner should match the theme of the rest of the app.
- We still want to retain the app heading, browse, and the GitHub button.

**Comment by atapas** [comment]
Hi @Ceesco, updated the description.

**Comment by Ceesco** [comment]
Hello Everyone. Great to be a part of the team. Much appreciated

**Comment by atapas** [comment]
> Hello Everyone. Great to be a part of the team. Much appreciated

Great to have you here, let's go .....

**Comment by atapas** [comment]
Hey @Deepak8717 , @Ceesco is looking into the design. Once he completes the first iteration and we review, we can guess by when we can start the coding.

Just for both of your info: We are targeting to merge it by 13th Sept 2022.

Looking forward to it.

**Comment by Ceesco** [comment]
![image](https://user-images.githubusercontent.com/104683015/189548648-d5f195da-d81c-4667-80ef-bee0f071865d.jpeg)....Hey everyone. I'm done with the banner design and delivered it to @Deepak8717 . Glad i could contribute to the growth of the platform. Much appreciated and cheers to y'all

**Comment by atapas** [comment]
Closing it as done.
