### ISSUE TITLE
✨ [Feature request]: Hackathon: Event landing page design

### ISSUE THREAD

**Issue by koustov** [reactplay/activities#11]
The idea of this feature is to design a reusable landing page for any event. For example, the immediate need is to host a hackathon. We wouldn't need to restructure this page every time a new hackathon appears in our timeline, rather tweaking some data and aesthetics
The page should contain 
- A well-defined banner
- Details of the event
- Partners information
- Collaborators/Sponsors information
- Registration link
- Project status
- Rules and regulations

**Comment by atapas** [comment]
Closing it as Done.
