### ISSUE TITLE
Spelling mistakes in FAQ section

### ISSUE THREAD

**Issue by UtkarshDixit-py** [reactplay/activities#127]
10th question in FAQ section -> "Is accouncing my particpation and progress on the social medis a must?" 

Corrections needed : 
announcing instead of accouncing
participation instead of particpation
media instead of medis

**Comment by atapas** [comment]
Thanks for pointing out @UtkarshDixit-py

**Comment by joshi-kaushal** [comment]
I would love to work on this!

**Comment by atapas** [comment]
> I would love to work on this!

Assigned

**Comment by UtkarshDixit-py** [comment]
@atapas I tried submitting the PR but it says i dont have access

**Comment by atapas** [comment]
@joshi-kaushal As you are fixing typos, just do an over all review and see if anything else gone off track.. Can fix all at once!

**Comment by atapas** [comment]
> @atapas I tried submitting the PR but it says i dont have access

OOPS! I can fix that. But I see @joshi-kaushal also started on it. Can one of you settle like who is working on it?

**Comment by UtkarshDixit-py** [comment]
@joshi-kaushal I have already made the changes just need to push changes.

**Comment by atapas** [comment]
> 

Btw, when you do not have permission go a public repo, you usually fork it and raise PR. I will give you the access anyway in a while, hoping you will continue to contribute here :)

**Comment by UtkarshDixit-py** [comment]
@atapas thanks for that, yeah i'll continue to contribute here

**Comment by atapas** [comment]
> @atapas thanks for that, yeah i'll continue to contribute here

Invited.
