### ISSUE TITLE
Spelling mistake in FAQ section

### ISSUE THREAD

**Issue by ashrrithk** [reactplay/activities#129]
**Describe the bug**
Spelling mistake in the FAQ page where "ReactJs is spelt as "RaectJs"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the faq section
2. Click on "Can I use anything other than React?"
3. The error is present in the answer.

**Expected behaviour**
The spelling must be "ReactJs"

**Screenshots**
![Screenshot 2023-01-31 at 11 49 49 AM](https://user-images.githubusercontent.com/30532534/215682196-92e76f35-8c12-43f8-8ed4-b9db0f6345c7.png)

**Comment by atapas** [comment]
Go ahead and fix it @ashrrithk 

Also, do an overall review of the texts so that can fix other mistakes too.

**Comment by ashrrithk** [comment]
@atapas I went through the texts on the landing page. It's all okay, except for the spelling that I mentioned.

**Comment by atapas** [comment]
Sure @ashrrithk fix that one then.
