### ISSUE TITLE
✨ [Feature request]: Hackathon: Idea lisitng page design

### ISSUE THREAD

**Issue by koustov** [reactplay/activities#4]
The objective of this feature is to come up with a reusable `idea` listing page for any sort of hackathon/hackfest program

The page should contain
- List of cards for each of the idea
  - A card will contain
    - Idea title
    - Idea description
    - Members/hackers image with name
    - Idea status

**Comment by Hat52** [comment]
Do you want a figma design?

**Comment by atapas** [comment]
Yes that's right

**Comment by Hat52** [comment]
https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1

Take a look at this design

**Comment by atapas** [comment]
> https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1
> 
> Take a look at this design

@Hat52 looks good... one point, there could be multiple owners for one idea. Can you incorporate into one card?

**Comment by atapas** [comment]
> > https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1
> > Take a look at this design
> 
> @Hat52 looks good... one point, there could be multiple owners for one idea. Can you incorporate into one card?

Also status can be

- Not Started
- In Progress
- Submitted

**Comment by Hat52** [comment]
On it

**Comment by atapas** [comment]
@Hat52 by any chance you are on our discord or somewhere for me to talk to you??

**Comment by Hat52** [comment]
@atapas I am not on your discord channel. Sahre the link and I will join .

**Comment by atapas** [comment]
> @atapas I am not on your discord channel. Sahre the link and I will join .

https://discord.gg/NYNTr4qS => ReactPlay Discord

**Comment by Hat52** [comment]
I have updated the design take a look at it.
https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1

**Comment by atapas** [comment]
> https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1

@Hat52 How about showing the members in this way?

![image](https://user-images.githubusercontent.com/3633137/188895678-cacaaa3a-473f-4e8d-ac55-56b38cedef0a.png)

On mouseover we can show the name and click on it, it will go to their github profile.

**Comment by atapas** [comment]
I think the Idea Title text can be bigger

**Comment by Hat52** [comment]
@atapas so once we hover on it then should we hide the image and display both name .

**Comment by Hat52** [comment]
@atapas the design is updated now. I have created two types of hover effect. First row has different hover effect and the second row has different hover effect.

**Comment by atapas** [comment]
> https://www.figma.com/file/LSSxDQEyFKIGczEiwe5pcS/Figma-design-for-hackathon-card?node-id=0%3A1

Thanks...

I can I see the hover effects?

One comment, better we put the Title at the left and the images at the right.

**Comment by shrilakshmishastry** [comment]
Are we going to keep the header and footer the same as the landing page? 
This question came into the picture as I can see only cards, not the header and footer.

**Comment by atapas** [comment]
> Are we going to keep the header and footer the same as the landing page?
> This question came into the picture as I can see only cards, not the header and footer.

Yes that right

**Comment by Hat52** [comment]
@atapas yes you can see the hover effect.

**Comment by Hat52** [comment]
@atapas  Figma updated

**Comment by shrilakshmishastry** [comment]
![image](https://user-images.githubusercontent.com/29778698/189538360-614ba180-a0af-488d-8b3b-88fbdd84df08.png)
These images are illustrated one or are we going to take a real image from user?

**Comment by atapas** [comment]
> ![image](https://user-images.githubusercontent.com/29778698/189538360-614ba180-a0af-488d-8b3b-88fbdd84df08.png)
> These images are illustrated/user avatar one or are we going to take a real image from user?

Of course you need to pull real image from db using graphql

**Comment by Hat52** [comment]
> ![image](https://user-images.githubusercontent.com/29778698/189538360-614ba180-a0af-488d-8b3b-88fbdd84df08.png)
> These images are illustrated/user avatar one or are we going to take a real image from user?

Yes you do have to get image dynamically. I just used these illustration to represent profile images.

**Comment by Hat52** [comment]
@atapas should we lock this design? If yes then I want to work on the coding side of this issue as well.

**Comment by atapas** [comment]
> @atapas should we lock this design? If yes then I want to work on the coding side of this issue as well.

Coding side @shrilakshmishastry is working on this. It would be great if you can do the design and coding of this one: https://github.com/reactplay/activities/issues/7

Let me know I can assign to you.

**Comment by Hat52** [comment]
Yes, I will work on it. But I will need little explanation on the fields.

**Comment by shrilakshmishastry** [comment]
Hi @Hat52  you have added the hover effect for what?

And do I need to make the card clickable? if so where will it be redirected?
If not 
![image](https://user-images.githubusercontent.com/29778698/189692707-41e3b1d2-3923-4dd9-8fd5-96aa7a5e52d7.png)
 is this button?

**Comment by Hat52** [comment]
@shrilakshmishastry their are two version of hover effect. Both rows have different hover effect. You can choose which ever you feel fit to our use case. And the use of the hover effect is when a user hovers on it we will display the name of the idea owner and the is going to be clickable. When we click on the name it should redirect to that person's profile. 
To answer your second question, For the time being the card is not clickable . I have discussed it with @atapas and he said once we complete the implementation of this design then we will move towards making it clickable.

**Comment by atapas** [comment]
Closing it as Done.
