### ISSUE TITLE
FAQ answer is not readable

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/activities#54]
**Describe the bug**
FAQ answers are not readable, it looks too dull.

**To Reproduce**
![image](https://user-images.githubusercontent.com/59080942/192135899-037422e3-f2ed-4863-8c2c-a4537d5ab374.png)

**Expected behavior**
We should change the answer's colour to make it readable.

**Comment by Sachin-chaurasiya** [comment]
Something like this would be better.

![image](https://user-images.githubusercontent.com/59080942/192136067-d9dba091-c026-4c66-bc85-d62b52f93a56.png)

**Comment by atapas** [comment]
Thanks @Sachin-chaurasiya 

Fix it
