### ISSUE TITLE
Idea main card not responsive 

### ISSUE THREAD

**Issue by yung-coder** [reactplay/activities#60]
**Describe the bug**
When we open submission and open any idea in a mobile device the box is not responsive.

**To Reproduce**
1. Go to view submissions 
2. Click on any of the ideas in mobile devices 
4. See error not responsive 

**Expected behavior**
It should be responsive and display correctly on all the devices 

**Screenshots**
![Screenshot_2022-09-25-15-48-30-24_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/94097778/192153244-3ee4d852-c39a-4da2-824c-102e955fd4e0.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: firefox 
 - Version: latest 

**Smartphone (please complete the following information):**
 - Device: realme x7
 - OS: Android 11
 - Browser: chrome 
 - Version: latest 

**Additional context**
I would like to fix it...

**Comment by yung-coder** [comment]
can i go for it @atapas ....?

**Comment by atapas** [comment]
> can i go for it @atapas ....?

Sure, please fix it with urgency

**Comment by yung-coder** [comment]
Okay i will fix it asap...
