### ISSUE TITLE
✨ [Feature request]: Hackathon: Registration page implementation

### ISSUE THREAD

**Issue by koustov** [reactplay/activities#7]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
- Only authenticated user can open this page
- Should have the following fields
  - Idea title [textbox]
  - Idea description [richtext]
  - Add member option:  Only registered members can be added(Max 2)

- The same page would be used for editing the information
- Only the owner can edit an idea

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Hat52** [comment]
-  why do we need to make Idea description  field rich text. And if we do, do I need to represent rich text field in the design or should I just represent it as a text area?
- Add member option:  is this field going to be a select box?
@atapas @koustov

**Comment by atapas** [comment]
> * why do we need to make Idea description  field rich text. And if we do, do we need to represent rich text field in the design or should we just represent it as a text area?
> * Add member option:  is this field going to be a select box?
>   @atapas @koustov

@Hat52 

Just use a Textarea for now for description 

yes the member option is a control that allows to select max of 2 owners from the list.

**Comment by Hat52** [comment]
Okay 👍

**Comment by Hat52** [comment]
https://www.figma.com/file/OZmPd8zGSUziafzPVJE0Un/Form-Design-template-%7C-BY-Sonia-(Community)?node-id=0%3A1

Here you go.
