### ISSUE TITLE
FAQS responsiveness 

### ISSUE THREAD

**Issue by yung-coder** [reactplay/activities#73]
**Describe the bug**
FAQS section looks way too expanded  in mobile devices.

**To Reproduce**
1. Go to FAQS (mobile devices)

**Expected behavior**
FAQS section should be more responsive in mobile devices.

**Screenshots**
![Screenshot_2022-09-30-12-42-04-59_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/94097778/193474142-8829fa3d-eb20-4ed3-94d9-f4ebe97f647f.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: firefox 
 - Version: latest 

**Smartphone (please complete the following information):**
 - Device: realme x7 
 - OS: Android 11
 - Browser: chrome 
 - Version: latest 

**Additional context**
I would like to work on this...

**Comment by ammaaraslam** [comment]
@yung-coder, go ahead with the fix, if you face any difficulties, ping in here or in the discord server

**Comment by yung-coder** [comment]
Sure @ammaaraslam

**Comment by ammaaraslam** [comment]
> Hey @ammaaraslam i have done it and going to open a pr i noticed a latest issue regarding FAQs
> 
> #74
> 
> It can be done in my issue just a margin top should i do it or leave...?

Ya sure go ahead

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by ammaaraslam** [comment]
> Hello Sir, Can You assign this issue to me?

Hi @Aniketmishra0!
Thanks for your willingness to contribute to the project. Unfortunately, @yung-coder is already working on this issue.
Please look into other issues if it interests you and also, you can check out the main [react-play repo](https://github.com/reactplay/react-play). There are plenty of issues to work on there.
