### ISSUE TITLE
[DOCS] Grammatical errors in README.md

### ISSUE THREAD

**Issue by shashankbhatgs** [reactplay/activities#78]
**Problem**
There are a few grammatical errors in the README.md file.

**What needs to be done?**
 - **Note**: We do checkin yarn.lock file. So it's adviced to use yarn package manager. If you need to use any other package manager,remove yarn.lock file from local directory first. Also, do not check in any other lock file.

**The above para needs to be changed to (the changes are highlighted)** 
-  **Note**: We do `check in` yarn.lock file. So it's `advised` to use yarn package manager. If you need to use any other package 
manager,` remove` yarn.lock file from `the` local directory first. Also, do not check in any other lock file.

<br>

**Screenshot of the exact paragraph from readme:** 

![Screenshot 2022-10-04 110812](https://user-images.githubusercontent.com/76593166/193742743-d0d80605-3d0b-4f38-9a0a-4c5b52732a41.png)

**Comment by shashankbhatgs** [comment]
Also, I would like to work on this, can I?

**Comment by Neeraj2002** [comment]
I would like to work on this issue!
