### ISSUE TITLE
✨ [Feature request]: Hackathon: Idea Listing page implementation

### ISSUE THREAD

**Issue by koustov** [reactplay/activities#8]
The idea of this feature is to implement an idea listing page for `nhost-reactplay hackathon`. 
The page should contain
- List of cards for each of the idea
  - A card will contain
    - Idea title
    - Idea description
    - Members/hackers image with name
    - Idea status
- A registration page link
- This page will be hosted under: https://hustles.reactplay.io/22/nhrphackathon/ideas

**Comment by atapas** [comment]
@shrilakshmishastry please check the design discussions here: https://github.com/reactplay/activities/issues/4
