### ISSUE TITLE
images not showing in judges and mentor section 

### ISSUE THREAD

**Issue by yung-coder** [reactplay/activities#93]
**Describe the bug**
Images of the judges (Johan Eliasson , Tapas Adhikary ) not showing.

**To Reproduce**
1. Go to home 
3. Scroll down to judges and mentors

**Expected behavior**
It should show all images properly

**Screenshots**
![judge](https://user-images.githubusercontent.com/94097778/196982705-cbfb02b5-7129-4d55-a889-b32e0ee1ff11.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Firefox
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: realme X7
 - OS: Android 11
 - Browser: chrome
 - Version: latest 

**Additional context**
I would like to fix it.

**Comment by kashish0604** [comment]
hey @yung-coder  can you please assign this issue to me. I can work on it

**Comment by kashish0604** [comment]
hi @yung-coder  can you please assign this issue to me. I can work on it

**Comment by yung-coder** [comment]
It's already assigned to me please look into some other issues.

**Comment by yung-coder** [comment]
Hey @ammaaraslam  i looked into it is occurring from  unavatar.io side its not properly fetching..

**Comment by yung-coder** [comment]
So,  like you are saying to download their profile images ...? 
@ammaaraslam

**Comment by ammaaraslam** [comment]
> So, like you are saying to download their profile images ...? @ammaaraslam

@yung-coder 
No... use the link to their twitter profile image and set it as the source of the image....
It's not the best practice... but for now, we'll have to roll with it

**Comment by yung-coder** [comment]
> > So, like you are saying to download their profile images ...? @ammaaraslam
> 
> @yung-coder No... use the link to their twitter profile image and set it as the source of the image.... It's not the best practice... but for now, we'll have to roll with it

i tried to get their profile images link but it is not  accessible as error (next/image`, hostname "twitter.com" is not configured under images in your `next.config.js`) ...?

**Comment by ammaaraslam** [comment]
> > > So, like you are saying to download their profile images ...? @ammaaraslam
> > 
> > 
> > @yung-coder No... use the link to their twitter profile image and set it as the source of the image.... It's not the best practice... but for now, we'll have to roll with it
> 
> i tried to get their profile images link but it is not accessible as error (next/image`, hostname "twitter.com" is not configured under images in your `next.config.js`) ...? @ammaaraslam
@yung-coder 

Ya for that... you have to add the domain of the image in `next.config.js`.
Like this:
```js
module.exports = {
  // other properties
  images: {
    domains: ['pbs.twimg.com'],
  },
}

```

**Comment by yung-coder** [comment]
> ```js
> 'pbs.twimg.com'
> ```

i tried it out it is not working @ammaaraslam

**Comment by ammaaraslam** [comment]
> > ```js
> > 'pbs.twimg.com'
> > ```
> 
> i tried it out it is not working @ammaaraslam
@yung-coder 
can you share any one profile link

**Comment by yung-coder** [comment]
https://twitter.com/tapasadhikary?t=-6PTcLnjoHFmXIV7HpQrUQ&s=09

**Comment by ammaaraslam** [comment]
> https://twitter.com/tapasadhikary?t=-6PTcLnjoHFmXIV7HpQrUQ&s=09

@yung-coder 

You're not taking the correct link...
- first go to the user's twitter profile
- click on the profile picture
- an enlarged version will be displayed
- right click on that image and **copy image address**

**Comment by yung-coder** [comment]
ohhhh got it i was getting the link from twiiter.com by bad now i think we should add the links to respective judges object and then it will be all good @ammaaraslam

**Comment by atapas** [comment]
No more reproducible.
